CREATE TABLE users(id VARCHAR PRIMARY KEY, name VARCHAR, email VARCHAR, password VARCHAR, phone INT DEFAULT 0, photo VARCHAR, message VARCHAR);

CREATE TABLE group(id SERIAL PRIMARY KEY, name VARCHAR DEFAULT'', participants VARCHAR DEFAULT'', message VARCHAR DEFAULT'');

